name: Daily News & Metro Notification
on:
  schedule:
    - cron: '0 21 * * *'  # 日本時間6:00 (ニュース+地下鉄情報)
  workflow_dispatch:

jobs:
  send-morning-info:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Enhanced Dify Workflow
        run: |
          curl -X POST 'https://api.dify.ai/v1/workflows/run' \
            --header 'Authorization: Bearer ${{ secrets.DIFY_API_KEY }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
              "inputs": {},
              "response_mode": "blocking",
              "user": "github-action"
            }'
