run: |
curl -X POST "https://api.dify.ai/v1/workflows/run" \
  -H "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
  -H "Content-Type: application/json" \
  -d '{
    "inputs": {},
    "response_mode": "blocking",
    "user": "github-action"
  }'
