run: |
curl -X POST 'https://api.dify.ai/v1/workflows/run' \
  --header 'Authorization: Bearer ${{ secrets.DIFY_API_KEY }}' \
  --header 'Content-Type: application/json' \
  --data-raw '{
    "inputs": {},
    "response_mode": "blocking",
    "user": "github-action"
  }'
